construction_homepage:
    path:     /constructions
    defaults: { _controller: ConstructionBundle:LoadData:load }

construction_add:
    path: /construction/add
    defaults: { _controller: ConstructionBundle:AddConstruction:AddConstruction }
    
construction_edit:
    path: /construction/edit/{id}
    defaults: { _controller: ConstructionBundle:EditConstruction:EditConstruction }