construction_homepage:
    path:     /constructions
    defaults: { _controller: ConstructionBundle:LoadConstruction:load }

construction_add:
    path: /construction/add
    defaults: { _controller: ConstructionBundle:AddConstruction:AddConstruction }
    
construction_edit:
    path: /construction/edit/{id}
    defaults: { _controller: ConstructionBundle:EditConstruction:EditConstruction }

construction_delete:
    path: /construction/delete
    defaults: { _controller: ConstructionBundle:AddConstruction:DeleteConstruction }

construction_details:
    path: /construction/details/{id}
    defaults: { _controller: ConstructionBundle:ShowDetails:ShowDetails }

equipment_list:
    path: /equipment/list
    defaults: { _controller: ConstructionBundle:LoadEquipment:load }