construction_homepage:
    path:     /constructions
    defaults: { _controller: ConstructionBundle:LoadConstruction:load }

construction_add:
    path: /construction/add
    defaults: { _controller: ConstructionBundle:AddConstruction:AddConstruction }
    
construction_edit:
    path: /construction/edit/{id}
    defaults: { _controller: ConstructionBundle:EditConstruction:EditConstruction }

construction_delete:
    path: /construction/delete
    defaults: { _controller: ConstructionBundle:AddConstruction:DeleteConstruction }

construction_details:
    path: /construction/details/{id}
    defaults: { _controller: ConstructionBundle:ShowDetails:ShowDetails }
    methods: GET

equipment_list:
    path: /equipment/list
    defaults: { _controller: ConstructionBundle:LoadEquipment:load }

equipment_add:
    path: /equipment/add
    defaults: { _controller: ConstructionBundle:AddEquipment:AddEquipment }

equipment_edit:
    path: /equipment/edit/{id}
    defaults: { _controller: ConstructionBundle:EditEquipment:EditEquipment }

equipment_delete:
    path: /equipment/delete
    defaults: { _controller: ConstructionBundle:AddEquipment:DeleteEquipment }

equipment_details:
    path: /equipment/details/{id}
    defaults: { _controller: ConstructionBundle:LoadEquipment:EquipmentDetails }

category_list:
    path: /category/list
    defaults: { _controller: ConstructionBundle:LoadCategory:load }

category_add:
    path: /category/add
    defaults: { _controller: ConstructionBundle:AddCategory:AddCategory }

category_edit:
    path: /category/edit/{id}
    defaults: { _controller: ConstructionBundle:EditCategory:EditCategory }

category_delete:
    path: /category/delete
    defaults: { _controller: ConstructionBundle:AddCategory:DeleteCategory }

update_assigned_equipment:
    path: /construction/details/{id}
    defaults: { _controller: ConstructionBundle:ShowDetails:UpdateAssignedEquipment }
    methods: POST